AWSTemplateFormatVersion: '2010-09-09'
Transform:                AWS::Serverless-2016-10-31
Description:              >
                          sam-app
                          Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 5

Parameters:
  Hoge:
    Type:    String
    Default: Default

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: learning-sam-ci-deploy_sample
      CodeUri:      dist/
      Handler:      sample
      Runtime:      go1.x
      Events:
        CWEvent:
          Type: Schedule
          Properties:
            Schedule:    'rate(1 minute)'
            Name:        SampleSchedule
            Description: sample schedule
            Enabled:     False
      Environment:
        Variables:
          HOGE: !Ref Hoge
  DeploySamCiSampleUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "deploy-sam-ci-sample"
      Path:     "/"
      Policies:
        -
          PolicyName: AllowSamDeploy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid:    "SamDeploy"
                Effect: "Allow"
                Action:
                  - "cloudformation:Describe*"
                  - "cloudformation:Get*"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:Create*"
                  - "cloudformation:Update*"
                Resource:
                  - "*"
              -
                Sid:    "SAMValidate"
                Effect: "Allow"
                Action:
                  - "iam:ListPolicies"
                Resource:
                  - "*"
              -
                Sid:    "SAMPackage"
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                Resource:
                  - "arn:aws:s3:::doriven-lambda-artifacts/learning-sam-ci-deploy/sample/*"
              -
                Sid:    "UpdateResourceByCF"
                Effect: "Allow"
                Action:
                  - "sns:*"
                  - "cloudwatch:*"
                  - "s3:Get*"
                  - "iam:List*"
                  - "iam:*Role*"
                  - "events:*"
                  - "lambda:*"
                  - "sqs:*"
                  - "logs:*"
                  - "ec2:Describe*"
                Resource:
                  - "*"
                Condition:
                  StringEquals:
                    'aws:CalledVia':
                      - cloudformation.amazonaws.com
