AWSTemplateFormatVersion: '2010-09-09'
Transform:                AWS::Serverless-2016-10-31
Description:              >
                          sam-app
                          Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 5

Parameters:
  Hoge:
    Type:    String
    Default: Default

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: learning-sam-ci-deploy_sample
      CodeUri:      dist/
      Handler:      sample
      Runtime:      go1.x
      Events:
        CWEvent:
          Type: Schedule
          Properties:
            Schedule:    'rate(1 minute)'
            Name:        SampleSchedule
            Description: sample schedule
            Enabled:     False
      Environment:
        Variables:
          HOGE: !Ref Hoge
